name: Testes Segurança

on:
  push:
  pull_request:

jobs:
  sqli-tests:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esperar DVWA iniciar e criar banco
        run: |
          echo "Aguardando DVWA ficar disponível..."
          for i in {1..30}; do
            if curl -s --fail http://localhost:8080/setup.php > /dev/null; then
              echo "DVWA está no ar!"
              break
            fi
            echo "Tentativa $i/30: DVWA ainda não respondeu"
            sleep 5
          done
          echo "Rodando setup do DVWA..."
          curl -s -L -X POST http://localhost:8080/setup.php --data "create_db=Create+%2F+Reset+Database"
          echo "Setup enviado. Aguardando 10 segundos para estabilização do banco..."
          sleep 10

      - name: Checar MariaDB e banco DVWA
        run: |
          echo "Verificando MariaDB e banco DVWA..."
          CONTAINER_ID=$(docker ps -q -f ancestor=vulnerables/web-dvwa)
          docker exec $CONTAINER_ID mysql -uroot -ppassword -e "SHOW DATABASES;"

      - name: Esperar DVWA ficar pronto
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8080/login.php | grep -q "Login"; then
              echo "DVWA pronto!"
              break
            fi
            echo "Aguardando DVWA... ($i/20)"
            sleep 5
          done

      - name: Rodar testes de SQL Injection
        env:
          BASE_URL: "http://localhost:8080"
        run: |
          echo "Aguardando DVWA estabilizar antes de iniciar testes..."
          sleep 5
          pytest -s -vv
