name: Testes Segurança

on:
  push:
  pull_request:

jobs:
  sqli-tests:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80
        options: >-
          --health-cmd "curl --silent --fail http://localhost:80/setup.php || exit 1"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=30

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esperar DVWA iniciar
        run: |
          echo "Aguardando DVWA ficar disponível..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/setup.php > /dev/null; then
              echo "DVWA está no ar!"
              exit 0
            fi
            echo "Tentativa $i/30: DVWA ainda não respondeu"
            sleep 5
          done
          echo "DVWA não subiu a tempo" && exit 1

      - name: Rodar setup do DVWA
        run: |
          echo "Rodando setup do DVWA..."
          curl -s -X POST http://localhost:8080/setup.php --data "create_db=Create%2B%2BSubmit" > /dev/null
          echo "Setup concluído!"

      - name: Checar MariaDB e banco DVWA
        run: |
          echo "Verificando MariaDB e banco DVWA..."
          CONTAINER_ID=$(docker ps -q -f ancestor=vulnerables/web-dvwa)
          for i in {1..20}; do
            docker exec $CONTAINER_ID mysql -uroot -proot -e "SHOW DATABASES;" && break
            echo "Tentativa $i/20: MariaDB ainda não está pronto..."
            sleep 5
          done

      - name: Rodar testes com pytest
        env:
          BASE_URL: "http://localhost:8080"
        run: pytest -s -vv
