name: Testes Segurança

on:
  push:
  pull_request:

jobs:
  sqli-tests:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80
        options: >-
          --health-cmd "curl --silent --fail http://localhost:80 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Esperar DVWA iniciar
        run: |
          echo "Aguardando DVWA ficar disponível..."
          for i in {1..15}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "DVWA está no ar!"
              exit 0
            fi
            echo "Tentativa $i/15: DVWA ainda não respondeu"
            sleep 5
          done
          echo "DVWA não subiu a tempo" && exit 1

      - name: Executar setup do DVWA
        run: |
          echo "Rodando setup do DVWA..."
          curl -s -X GET http://localhost:8080/setup.php > /dev/null
          curl -s -X POST http://localhost:8080/setup.php --data "create_db=Create%2B%2BSubmit" > /dev/null
          echo "Setup concluído!"

      - name: Rodar testes com pytest
        env:
          BASE_URL: "http://localhost:8080"
        run: pytest -s -vv
