name: Testes de Segurança com DVWA

# Define os gatilhos para o workflow
on:
  # Executa em pushes para os branches principais
  push:
    branches: [ main, master ]
  # Executa em pull requests para os branches principais
  pull_request:
    branches: [ main, master ]
  # Permite que você execute este workflow manualmente na aba "Actions"
  workflow_dispatch:

jobs:
  sqli-tests:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80
        # A verificação de saúde automática (healthcheck) foi removida.
        # A verificação de prontidão será feita manualmente no script abaixo.

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aguardar DVWA e Resetar Banco de Dados
        run: |
          echo "Aguardando o serviço DVWA ficar disponível..."
          # Loop que tenta se conectar ao DVWA por até 2 minutos.
          for i in {1..24}; do
            if curl -s --fail http://localhost:8080/login.php > /dev/null; then
              echo "DVWA está online!"
              break
            fi
            echo "Tentativa $i/24: DVWA ainda não respondeu. Aguardando 5 segundos..."
            sleep 5
          done

          # Verifica se o loop terminou sem sucesso
          if ! curl -s --fail http://localhost:8080/login.php > /dev/null; then
            echo "::error::O serviço DVWA não ficou disponível após 2 minutos."
            exit 1
          fi
          
          echo "Obtendo token CSRF da página de setup..."
          USER_TOKEN=$(curl -s -c cookies.txt http://localhost:8080/setup.php | grep 'user_token' | sed -n "s/.*value='\(.*\)'.*/\1/p")
          
          if [ -z "$USER_TOKEN" ]; then
            echo "::error::Falha ao obter o token CSRF (user_token) da página de setup."
            exit 1
          fi
          echo "Token CSRF obtido com sucesso."

          echo "Enviando requisição para criar/resetar o banco de dados..."
          curl -s -L -b cookies.txt -X POST http://localhost:8080/setup.php \
            --data-urlencode "user_token=${USER_TOKEN}" \
            --data-urlencode "create_db=Create / Reset Database"
          
          echo "Banco de dados resetado. Aguardando 20 segundos para a aplicação estabilizar..."
          sleep 20

      - name: Verificar se a página de login está pronta
        run: |
          echo "Verificando se a página de login está acessível após o reset do DB..."
          curl -s --fail http://localhost:8080/login.php | grep -i "Login"

      - name: Rodar testes de SQL Injection
        env:
          BASE_URL: "http://localhost:8080"
        run: |
          pytest -s -vv
