name: Testes Segurança

on:
  push:
  pull_request:

jobs:
  sqli-tests:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esperar DVWA iniciar
        run: |
          echo "Aguardando DVWA ficar disponível..."
          for i in {1..30}; do
            if curl -s --fail http://localhost:8080/setup.php > /dev/null; then
              echo "DVWA está no ar!"
              exit 0
            fi
            echo "Tentativa $i/30: DVWA ainda não respondeu"
            sleep 5
          done
          echo "Erro: DVWA não subiu a tempo." && exit 1

      - name: Rodar setup do DVWA e garantir estabilidade
        run: |
          echo "Rodando setup do DVWA..."
          # Envia o formulário para criar/resetar o banco de dados. A flag -L segue o redirect para login.php
          curl -s -L -X POST http://localhost:8080/setup.php --data "create_db=Create+%2F+Reset+Database"

          echo "Setup enviado. Aguardando 10 segundos para o banco de dados estabilizar..."
          sleep 10

          echo "Verificando se a página de login está pronta..."
          # Acessa a página de login para garantir que a aplicação está no estado esperado.
          curl --fail http://localhost:8080/login.php
          echo "DVWA está pronto para os testes."

      - name: Checar MariaDB e banco DVWA
        run: |
          echo "Verificando MariaDB e banco DVWA..."
          CONTAINER_ID=$(docker ps -q -f ancestor=vulnerables/web-dvwa)
          # A senha padrão é 'password', não 'root'
          docker exec $CONTAINER_ID mysql -uroot -ppassword -e "SHOW DATABASES;"

      - name: Rodar testes com pytest
        env:
          BASE_URL: "http://localhost:8080"
        run: pytest -s -vv
